import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_FILE = BASE_DIR / "src" / "data" / "peptides.js"

category_defaults = {
    "Growth Hormone Secretagogues": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 2.0,
        "timing": "Evening before sleep or post-workout",
        "base_overview": (
            "a growth hormone releasing peptide used to enhance pulsatile GH secretion, support recovery, and "
            "promote lean mass while managing fat metabolism."
        ),
        "base_steps": [
            "Allow the lyophilized powder to reach room temperature without removing the stopper.",
            "Slowly inject bacteriostatic water down the side of the vial to avoid foaming.",
            "Gently swirl (do not shake) until the powder dissolves fully. Store refrigerated."
        ],
    },
    "Muscle & Recovery": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 3.0,
        "timing": "Post-training or split AM/PM depending on protocol",
        "base_overview": (
            "an anabolic-support peptide favored for accelerating soft-tissue healing, enhancing muscle protein "
            "synthesis, and reducing downtime between training sessions."
        ),
        "base_steps": [
            "Let the vial warm to room temperature before reconstitution.",
            "Add bacteriostatic water slowly along the glass wall to protect peptide integrity.",
            "Roll between the palms to mix until clear; refrigerate between uses."
        ],
    },
    "Metabolic & Weight Management": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 2.5,
        "timing": "Morning pre-breakfast or pre-activity",
        "base_overview": (
            "a metabolic-support peptide employed to improve insulin sensitivity, upregulate mitochondrial function, "
            "and assist with gradual fat reduction when paired with nutrition."
        ),
        "base_steps": [
            "Warm vial to room temperature and swab the stopper with alcohol.",
            "Reconstitute with bacteriostatic water down the inside of the vial.",
            "Rotate gently to dissolve; avoid vigorous shaking. Keep refrigerated."
        ],
    },
    "Cognitive & Neurological": {
        "diluent": "Sterile saline",
        "volume_ml": 2.0,
        "timing": "Morning or pre-cognitive demand",
        "base_overview": (
            "a neuroactive peptide utilized to improve cognitive resilience, modulate neurotrophic factors, and support "
            "stress adaptation."
        ),
        "base_steps": [
            "Bring vial to room temperature and disinfect the stopper.",
            "Add sterile saline dropwise to minimize foaming.",
            "Tilt and rotate gently until powder dissolves fully; refrigerate afterwards."
        ],
    },
    "Immune & Inflammatory Modulation": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 1.5,
        "timing": "Morning or around immune stressors",
        "base_overview": (
            "an immunomodulatory peptide chosen to rebalance inflammatory signaling, bolster innate defense, and speed "
            "recovery from immune challenges."
        ),
        "base_steps": [
            "Allow vial to reach room temperature and cleanse the stopper.",
            "Slowly inject bacteriostatic water while aiming the stream at the glass wall.",
            "Swirl gently until clear; store in the refrigerator."
        ],
    },
    "Sexual Health & Vitality": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 1.0,
        "timing": "As needed 30-60 minutes prior to intimacy or on scheduled days",
        "base_overview": (
            "a peptide formulated to enhance sexual arousal, improve vascular responsiveness, and support overall vitality "
            "in both men and women."
        ),
        "base_steps": [
            "Warm vial to ambient temperature before reconstitution.",
            "Inject bacteriostatic water slowly down the side of the vial.",
            "Rotate gently until dissolved; refrigerate following reconstitution."
        ],
    },
    "Dermal & Aesthetic Support": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 5.0,
        "timing": "Evening or pre-sleep for systemic cosmetic peptides",
        "base_overview": (
            "a cosmetic-support peptide leveraged to stimulate collagen remodeling, improve skin tone, and address "
            "pigmentation irregularities."
        ),
        "base_steps": [
            "Sanitize the rubber stopper and allow the vial to warm slightly.",
            "Add bacteriostatic water carefully to avoid frothing.",
            "Invert gently several times until mixed; refrigerate between uses."
        ],
    },
    "Cardiometabolic & Vascular": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 2.0,
        "timing": "Morning with cardiometabolic regimen",
        "base_overview": (
            "a vascular-support peptide employed to enhance endothelial function, balance blood pressure, and optimize "
            "cardiometabolic resilience."
        ),
        "base_steps": [
            "Bring vial to room temperature and swab the stopper.",
            "Direct bacteriostatic water along the vial wall while reconstituting.",
            "Swirl gently until fully dissolved; refrigerate."
        ],
    },
    "Gastrointestinal & Barrier Integrity": {
        "diluent": "Bacteriostatic water",
        "volume_ml": 2.0,
        "timing": "Morning or away from meals",
        "base_overview": (
            "a gut-support peptide adopted to reinforce mucosal integrity, calm inflammation, and hasten healing following "
            "GI stress."
        ),
        "base_steps": [
            "Allow vial to acclimate to room temperature and sterilize the stopper.",
            "Introduce bacteriostatic water slowly while aiming at the glass wall.",
            "Swirl softly until clear; refrigerate and use within 30 days."
        ],
    },
    "Longevity & Cellular Optimization": {
        "diluent": "Sterile saline",
        "volume_ml": 2.0,
        "timing": "Evening or as part of longevity protocols",
        "base_overview": (
            "a cellular-support peptide applied to regulate circadian signaling, DNA repair pathways, and overall "
            "longevity biomarkers."
        ),
        "base_steps": [
            "Let the vial reach room temperature and prep with an alcohol swab.",
            "Add sterile saline along the glass to maintain peptide stability.",
            "Rotate gently until dissolved; store refrigerated."
        ],
    },
}

peptide_definitions = [
    {
        "id": "ghs-1",
        "name": "CJC-1295 w/ DAC",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Drug Affinity Complex extends half-life of GHRH analog for sustained GH pulses",
        "focus": "sustained GH release, recovery, and lean mass preservation",
        "benefits": [
            "Elevates GH/IGF-1 for longer windows",
            "Supports tissue repair after intense training",
            "Improves sleep quality by reinforcing nocturnal GH pulses",
        ],
        "loading": "2 mg once weekly for 6 weeks",
        "maintenance": "2 mg every 10-14 days",
        "timing": "Evening subcutaneous administration",
        "notes": "Pair with short-acting secretagogues to mimic physiologic pulses.",
    },
    {
        "id": "ghs-2",
        "name": "CJC-1295 (Mod-GRF 1-29)",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Short-acting GHRH analog supporting physiologic pulse frequency",
        "focus": "GH pulse amplification without prolonged elevation",
        "benefits": [
            "Pairs well with GHRPs for synergistic GH release",
            "Minimal prolactin or cortisol spillover",
            "Supports improved recovery sleep architecture",
        ],
        "loading": "100 mcg pre-bed and pre-training for 6 weeks",
        "maintenance": "100 mcg nightly ongoing",
        "timing": "30 minutes before meals to avoid insulin interference",
        "notes": "Stack with ipamorelin for a balanced GH secretagogue protocol.",
    },
    {
        "id": "ghs-3",
        "name": "Ipamorelin",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Selective ghrelin receptor agonist promoting GH release with minimal side effects",
        "focus": "gentle GH pulses and appetite neutrality",
        "benefits": [
            "Low risk of hunger spikes compared to GHRP-6",
            "Minimal impact on prolactin or cortisol",
            "Supports connective tissue healing in combo protocols",
        ],
        "loading": "300 mcg pre-bed for 8 weeks",
        "maintenance": "200 mcg nightly",
        "timing": "Administer on an empty stomach",
        "notes": "Frequently combined with CJC-1295 for synergistic effect.",
    },
    {
        "id": "ghs-4",
        "name": "GHRP-2",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Potent ghrelin mimetic triggering GH release and mild appetite stimulation",
        "focus": "robust GH pulses with metabolic flexibility",
        "benefits": [
            "Rapid onset GH spike supports anabolic signaling",
            "Slight increase in appetite aids hard gainers",
            "Pairs with Mod-GRF for twice-daily GH pulses",
        ],
        "loading": "150 mcg three times daily for 4 weeks",
        "maintenance": "150 mcg twice daily",
        "timing": "Morning, post-training, and pre-bed on empty stomach",
        "notes": "Monitor for water retention in sensitive users.",
    },
    {
        "id": "ghs-5",
        "name": "GHRP-6",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Ghrelin receptor agonist with pronounced hunger signaling",
        "focus": "strong GH and appetite response for mass gaining phases",
        "benefits": [
            "Large GH spikes ideal for bulking cycles",
            "Enhances gastric motility and hunger",
            "Useful in injury recovery when nutrition is high",
        ],
        "loading": "150 mcg pre-breakfast and pre-bed for 6 weeks",
        "maintenance": "100 mcg twice daily",
        "timing": "Take before meals to leverage appetite increase",
        "notes": "Avoid if struggling with glucose regulation or appetite control.",
    },
    {
        "id": "ghs-6",
        "name": "Hexarelin",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Strong ghrelin mimetic delivering maximal GH pulse amplitude",
        "focus": "short bursts of GH for advanced physique recomposition",
        "benefits": [
            "Highest GH release among GHRPs",
            "Supports tendon and ligament repair",
            "May modestly aid fat loss via elevated IGF-1",
        ],
        "loading": "100 mcg twice daily for 4 weeks",
        "maintenance": "Cycle 4 weeks on, 4 weeks off",
        "timing": "Morning and evening away from carbs",
        "notes": "Monitor lipids and insulin sensitivity during longer runs.",
    },
    {
        "id": "ghs-7",
        "name": "Tesamorelin",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Synthetic GHRH analog with lipolytic bias for visceral fat reduction",
        "focus": "targeted reduction of visceral adiposity",
        "benefits": [
            "Improves triglyceride profile and waist circumference",
            "Enhances sleep architecture through GH normalization",
            "Supports cognitive clarity via IGF-1 modulation",
        ],
        "loading": "2 mg subcutaneous nightly for 12 weeks",
        "maintenance": "2 mg every other night",
        "timing": "Administer before bedtime on empty stomach",
        "notes": "Track fasting glucose and IGF-1 levels periodically.",
    },
    {
        "id": "ghs-8",
        "name": "Sermorelin",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "GHRH analog promoting endogenous GH production with physiologic rhythm",
        "focus": "long-term GH optimization in aging clients",
        "benefits": [
            "Gradual improvement in body composition",
            "Supports restorative sleep and energy",
            "Enhances skin elasticity over time",
        ],
        "loading": "500 mcg nightly for 12 weeks",
        "maintenance": "300 mcg nightly",
        "timing": "Take pre-bed separated from food by 2 hours",
        "notes": "Encourage lifestyle strategies to maximize GH release (sleep, fasting).",
    },
    {
        "id": "ghs-9",
        "name": "Ibutamoren (MK-677)",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Oral ghrelin receptor agonist extending GH and IGF-1 elevation",
        "focus": "daily GH support without injections",
        "benefits": [
            "Convenient oral dosing",
            "Improves REM sleep quality",
            "Supports bone density and connective tissue",
        ],
        "loading": "25 mg orally nightly for 12 weeks",
        "maintenance": "12.5-25 mg nightly",
        "timing": "Evening with light snack to offset hunger",
        "notes": "Monitor fasting glucose and appetite changes.",
    },
    {
        "id": "ghs-10",
        "name": "PEG-MGF",
        "category": "Growth Hormone Secretagogues",
        "mechanism": "Pegylated mechano growth factor sustaining IGF-1 splice activation",
        "focus": "local muscle repair following heavy training",
        "benefits": [
            "Extends activation of satellite cells",
            "Reduces DOMS in targeted muscle groups",
            "Pairs with IGF-1 LR3 for mass phases",
        ],
        "loading": "200 mcg post-workout to trained muscle for 4 weeks",
        "maintenance": "Use post-intense sessions only",
        "timing": "Immediately post-training",
        "notes": "Rotate injection sites to avoid irritation.",
    },
    {
        "id": "mr-1",
        "name": "BPC-157",
        "category": "Muscle & Recovery",
        "mechanism": "Body protective compound accelerating angiogenesis and fibroblast activity",
        "focus": "rapid soft-tissue and gut repair",
        "benefits": [
            "Supports tendon and ligament healing",
            "Improves gastric mucosal integrity",
            "Reduces inflammatory signaling around injuries",
        ],
        "loading": "250 mcg twice daily for 6 weeks",
        "maintenance": "250 mcg daily as needed",
        "timing": "Morning and evening, ideally near injury site",
        "notes": "Oral capsules can complement injections for GI support.",
    },
    {
        "id": "mr-2",
        "name": "TB-500 (Thymosin Beta-4 Fragment)",
        "category": "Muscle & Recovery",
        "mechanism": "Acts on actin regulation to enhance cellular migration and repair",
        "focus": "systemic healing and recovery",
        "benefits": [
            "Accelerates recovery from musculoskeletal injuries",
            "Improves flexibility by reducing scar tissue",
            "Enhances hair and skin quality as collateral benefit",
        ],
        "loading": "2 mg twice weekly for 6 weeks",
        "maintenance": "2 mg monthly",
        "timing": "Morning or post-therapy sessions",
        "notes": "Combine with BPC-157 for comprehensive tissue repair.",
    },
    {
        "id": "mr-3",
        "name": "Follistatin 344",
        "category": "Muscle & Recovery",
        "mechanism": "Myostatin antagonist allowing greater muscle fiber hypertrophy",
        "focus": "short-term lean mass accrual",
        "benefits": [
            "Promotes rapid strength increases",
            "Works synergistically with resistance training",
            "Helps break plateaus in advanced athletes",
        ],
        "loading": "100 mcg daily for 20 days",
        "maintenance": "Cycle 90 days off before repeating",
        "timing": "Evening or post-workout",
        "notes": "Support liver health and monitor lipids during cycles.",
    },
    {
        "id": "mr-4",
        "name": "Follistatin 315",
        "category": "Muscle & Recovery",
        "mechanism": "Alternative myostatin binding isoform with shorter active window",
        "focus": "targeted hypertrophy phases",
        "benefits": [
            "Assists in localized muscle growth",
            "Shorter activity allows precise cycling",
            "Supports connective tissue resilience",
        ],
        "loading": "200 mcg every other day for 3 weeks",
        "maintenance": "Cycle off for at least 8 weeks",
        "timing": "Post-workout on training days",
        "notes": "Avoid stacking with other strong growth agents without oversight.",
    },
    {
        "id": "mr-5",
        "name": "IGF-1 LR3",
        "category": "Muscle & Recovery",
        "mechanism": "Extended half-life IGF-1 analog supporting muscle protein synthesis",
        "focus": "systemic hypertrophy and nutrient partitioning",
        "benefits": [
            "Increases amino acid uptake into muscle",
            "Improves insulin sensitivity when dosed moderately",
            "Supports lean mass retention during cutting phases",
        ],
        "loading": "40 mcg post-workout for 30 days",
        "maintenance": "20 mcg on training days",
        "timing": "Immediately post-training with carbs",
        "notes": "Rotate injection sites and monitor blood glucose.",
    },
    {
        "id": "mr-6",
        "name": "IGF-1 DES (1-3)",
        "category": "Muscle & Recovery",
        "mechanism": "Short-acting IGF-1 variant targeting local muscle receptors",
        "focus": "site-specific muscle hyperplasia",
        "benefits": [
            "Ideal for localized lagging muscle groups",
            "Minimal systemic hypoglycemia risk",
            "Pairs with mechanical tension for best results",
        ],
        "loading": "50 mcg per muscle head post-workout for 4 weeks",
        "maintenance": "Use during specialization phases only",
        "timing": "Immediately post training on target muscle",
        "notes": "Limit duration to prevent receptor desensitization.",
    },
    {
        "id": "mr-7",
        "name": "PEG-IGF-1",
        "category": "Muscle & Recovery",
        "mechanism": "Pegylated IGF-1 for prolonged anabolic support",
        "focus": "long-duration IGF signaling",
        "benefits": [
            "Provides steady-state IGF activity",
            "Reduces frequency of injections",
            "Supports connective tissue in high-volume training",
        ],
        "loading": "1 mg weekly for 4 weeks",
        "maintenance": "1 mg every other week",
        "timing": "Morning or post-training",
        "notes": "Coordinate with nutrition professionals to avoid insulin overlap.",
    },
    {
        "id": "mr-8",
        "name": "Myostatin Inhibiting Peptide",
        "category": "Muscle & Recovery",
        "mechanism": "Competitive binder reducing myostatin activity",
        "focus": "breakthrough hypertrophy potential",
        "benefits": [
            "Enables new muscle tissue accrual",
            "Best suited for advanced trainees",
            "Synergistic with high-protein diet",
        ],
        "loading": "1 mg weekly for 4 weeks",
        "maintenance": "Cycle off 12 weeks before repeating",
        "timing": "Morning on rest days",
        "notes": "Medical supervision recommended due to potency.",
    },
    {
        "id": "mr-9",
        "name": "GHK-Cu Injectable",
        "category": "Muscle & Recovery",
        "mechanism": "Copper peptide that modulates tissue remodeling and angiogenesis",
        "focus": "soft tissue repair with cosmetic benefits",
        "benefits": [
            "Improves wound healing speed",
            "Supports hair and skin vitality",
            "Assists with post-surgical recovery",
        ],
        "loading": "200 mcg daily for 6 weeks",
        "maintenance": "100 mcg daily",
        "timing": "Evening or post-therapy sessions",
        "notes": "Can be paired with topical GHK-Cu for aesthetic focus.",
    },
    {
        "id": "mr-10",
        "name": "MGF (Mechano Growth Factor)",
        "category": "Muscle & Recovery",
        "mechanism": "Local IGF-1 splice variant activated by mechanical loading",
        "focus": "post-training repair and muscle satellite cell activation",
        "benefits": [
            "Improves recovery of damaged fibers",
            "Supports new muscle cell formation",
            "Useful after eccentric-heavy sessions",
        ],
        "loading": "100 mcg per trained muscle group post-workout for 4 weeks",
        "maintenance": "Use only after priority sessions",
        "timing": "Immediately post-training",
        "notes": "Pair with adequate amino acids to support growth.",
    },
    {
        "id": "met-1",
        "name": "AOD 9604",
        "category": "Metabolic & Weight Management",
        "mechanism": "Fragment of HGH that promotes lipolysis without affecting blood sugar",
        "focus": "stubborn fat mobilization",
        "benefits": [
            "Targets adipose tissue without GH side effects",
            "Supports joint cartilage health",
            "Useful for plateau busting during fat loss",
        ],
        "loading": "300 mcg daily for 12 weeks",
        "maintenance": "150 mcg daily",
        "timing": "Morning fasted",
        "notes": "Combine with caloric deficit for best outcomes.",
    },
    {
        "id": "met-2",
        "name": "5-Amino-1MQ",
        "category": "Metabolic & Weight Management",
        "mechanism": "Inhibits NNMT to enhance cellular metabolism and NAD+ availability",
        "focus": "metabolic rate elevation",
        "benefits": [
            "Enhances basal metabolic expenditure",
            "Supports healthy adiponectin levels",
            "Pairs with strength training to maintain lean mass",
        ],
        "loading": "50 mg orally daily for 8 weeks",
        "maintenance": "25 mg daily",
        "timing": "Morning with first meal",
        "notes": "Monitor blood pressure and hydration.",
    },
    {
        "id": "met-3",
        "name": "MOTS-c",
        "category": "Metabolic & Weight Management",
        "mechanism": "Mitochondrial derived peptide improving insulin sensitivity and AMPK activation",
        "focus": "glucose control and mitochondrial health",
        "benefits": [
            "Supports endurance performance",
            "Improves glucose uptake in skeletal muscle",
            "May reduce visceral fat accumulation",
        ],
        "loading": "10 mg weekly for 4 weeks",
        "maintenance": "10 mg biweekly",
        "timing": "Morning pre-exercise",
        "notes": "Stack with exercise mimetics carefully to avoid overtraining.",
    },
    {
        "id": "met-4",
        "name": "Amlexanox Peptide",
        "category": "Metabolic & Weight Management",
        "mechanism": "Inhibits TBK1/IKKe to improve metabolic rate and insulin sensitivity",
        "focus": "insulin sensitization",
        "benefits": [
            "Supports reduction in liver fat",
            "Improves glycemic control",
            "May enhance mood through anti-inflammatory pathways",
        ],
        "loading": "100 mg orally daily for 12 weeks",
        "maintenance": "50 mg daily",
        "timing": "Morning with breakfast",
        "notes": "Assess liver enzymes periodically.",
    },
    {
        "id": "met-5",
        "name": "GLP-1 Analog Peptide",
        "category": "Metabolic & Weight Management",
        "mechanism": "Glucagon-like peptide-1 receptor agonist improving satiety and insulin secretion",
        "focus": "appetite control and glycemic balance",
        "benefits": [
            "Significant appetite reduction",
            "Supports A1c improvement",
            "May decrease cardiovascular risk markers",
        ],
        "loading": "0.25 mg weekly titrated up to 1 mg",
        "maintenance": "0.5-1 mg weekly",
        "timing": "Any time of day with consistent schedule",
        "notes": "Educate on managing GI side effects during titration.",
    },
    {
        "id": "met-6",
        "name": "GIP/GLP-1 Dual Agonist",
        "category": "Metabolic & Weight Management",
        "mechanism": "Dual incretin mimetic improving insulin secretion and energy expenditure",
        "focus": "comprehensive metabolic reset",
        "benefits": [
            "Greater weight loss than single incretins",
            "Enhances insulin sensitivity",
            "Supports cardiovascular biomarkers",
        ],
        "loading": "2.5 mg weekly titrated to 10 mg",
        "maintenance": "5-10 mg weekly",
        "timing": "Consistent weekly schedule",
        "notes": "Monitor GI tolerance and hydration closely.",
    },
    {
        "id": "met-7",
        "name": "Tesofensine Peptide",
        "category": "Metabolic & Weight Management",
        "mechanism": "Triple monoamine reuptake inhibitor enhancing satiety and energy expenditure",
        "focus": "appetite suppression with energy uplift",
        "benefits": [
            "Boosts calorie burn during resting",
            "Reduces cravings and snacking",
            "Supports mood during caloric deficit",
        ],
        "loading": "0.25 mg daily for 4 weeks",
        "maintenance": "0.25-0.5 mg daily",
        "timing": "Morning to avoid insomnia",
        "notes": "Screen for cardiovascular history before use.",
    },
    {
        "id": "met-8",
        "name": "Melanotan II Microdose",
        "category": "Metabolic & Weight Management",
        "mechanism": "Melanocortin receptor agonist affecting appetite and lipolysis",
        "focus": "dual tanning and appetite control",
        "benefits": [
            "Reduces appetite and snacking",
            "Enhances energy expenditure",
            "Provides gradual pigmentation for sun protection",
        ],
        "loading": "250 mcg daily for 2 weeks",
        "maintenance": "250 mcg 2-3x weekly",
        "timing": "Evening to mitigate nausea",
        "notes": "Advise on sun exposure management and hydration.",
    },
    {
        "id": "met-9",
        "name": "Lipo-Shot Peptide Blend",
        "category": "Metabolic & Weight Management",
        "mechanism": "Combination of MIC (methionine, inositol, choline) with carnitine for fat mobilization",
        "focus": "support hepatic fat export",
        "benefits": [
            "Improves liver fat processing",
            "Supports energy during low-calorie diets",
            "Pairs with interval training for best results",
        ],
        "loading": "1 mL IM twice weekly for 8 weeks",
        "maintenance": "1 mL weekly",
        "timing": "Morning on cardio days",
        "notes": "Ensure adequate B-vitamin intake during use.",
    },
    {
        "id": "met-10",
        "name": "Fragment 176-191",
        "category": "Metabolic & Weight Management",
        "mechanism": "HGH fragment targeting adipocyte lipolysis without affecting blood glucose",
        "focus": "fat oxidation and stubborn area reduction",
        "benefits": [
            "Spot reduction aid when combined with lifestyle",
            "Low risk of GH-related side effects",
            "Improves lipid metabolism markers",
        ],
        "loading": "500 mcg daily split AM/PM for 12 weeks",
        "maintenance": "250 mcg daily",
        "timing": "Morning fasted and pre-bed",
        "notes": "Synergistic with AOD 9604 during cutting phases.",
    },
    {
        "id": "neuro-1",
        "name": "Semax",
        "category": "Cognitive & Neurological",
        "mechanism": "ACTH(4-10) analog increasing BDNF and neurotrophic signaling",
        "focus": "acute cognitive performance",
        "benefits": [
            "Enhances focus and mental clarity",
            "Supports recovery from cognitive fatigue",
            "May reduce anxiety under stress",
        ],
        "loading": "300 mcg intranasal twice daily for 10 days",
        "maintenance": "300 mcg as needed",
        "timing": "Morning and mid-day",
        "notes": "Cycle 10 days on, 10 days off for sustained benefits.",
    },
    {
        "id": "neuro-2",
        "name": "Selank",
        "category": "Cognitive & Neurological",
        "mechanism": "Tuftsin analog modulating GABA and serotonin pathways",
        "focus": "anxiolytic cognitive support",
        "benefits": [
            "Reduces anxiety without sedation",
            "Supports immune modulation",
            "Improves resilience to stress",
        ],
        "loading": "300 mcg intranasal three times daily for 14 days",
        "maintenance": "300 mcg twice daily",
        "timing": "Morning and afternoon",
        "notes": "Can be paired with Semax alternating doses for balanced effect.",
    },
    {
        "id": "neuro-3",
        "name": "N-Acetyl Semax Amidate",
        "category": "Cognitive & Neurological",
        "mechanism": "Modified Semax analog with extended activity and dopaminergic modulation",
        "focus": "sustained cognitive drive",
        "benefits": [
            "Longer-lasting motivation and alertness",
            "Supports neuroplasticity",
            "Reduces mental fatigue during demanding projects",
        ],
        "loading": "300 mcg intranasal twice daily for 5 days",
        "maintenance": "150-300 mcg as needed",
        "timing": "Morning pre-work",
        "notes": "Avoid late-day dosing to prevent insomnia.",
    },
    {
        "id": "neuro-4",
        "name": "Dihexa",
        "category": "Cognitive & Neurological",
        "mechanism": "Angiotensin IV analog promoting synaptogenesis",
        "focus": "long-term neuroregeneration",
        "benefits": [
            "Enhances memory consolidation",
            "Supports synaptic repair",
            "Potential adjunct in neurodegenerative protocols",
        ],
        "loading": "10 mg oral or sublingual daily for 8 weeks",
        "maintenance": "5 mg daily",
        "timing": "Morning",
        "notes": "Pair with choline donors to support acetylcholine synthesis.",
    },
    {
        "id": "neuro-5",
        "name": "Cerebrolysin Peptide Mix",
        "category": "Cognitive & Neurological",
        "mechanism": "Neurotrophic peptide blend enhancing neuronal survival",
        "focus": "neuroprotection and recovery",
        "benefits": [
            "Supports post-stroke rehabilitation",
            "Improves processing speed",
            "Reduces neuroinflammation",
        ],
        "loading": "10 mL IM daily for 10 days",
        "maintenance": "10 mL twice weekly",
        "timing": "Morning or early afternoon",
        "notes": "Use medical supervision for parenteral administration.",
    },
    {
        "id": "neuro-6",
        "name": "Noopept Injectable",
        "category": "Cognitive & Neurological",
        "mechanism": "Promotes NGF and BDNF expression enhancing memory and focus",
        "focus": "daily cognitive enhancement",
        "benefits": [
            "Improves working memory",
            "Supports neurovascular coupling",
            "May alleviate oxidative stress in neurons",
        ],
        "loading": "20 mg IM daily for 25 days",
        "maintenance": "10 mg IM three times weekly",
        "timing": "Morning",
        "notes": "Monitor for irritability; adjust dose accordingly.",
    },
    {
        "id": "neuro-7",
        "name": "P21 Peptide",
        "category": "Cognitive & Neurological",
        "mechanism": "BDNF mimetic promoting hippocampal neurogenesis",
        "focus": "memory rescue",
        "benefits": [
            "Supports memory consolidation",
            "Improves focus under stress",
            "May enhance mood via neurotrophic pathways",
        ],
        "loading": "1 mg subcutaneous daily for 10 days",
        "maintenance": "1 mg twice weekly",
        "timing": "Morning or pre-study",
        "notes": "Combine with omega-3s to enhance synaptic plasticity.",
    },
    {
        "id": "neuro-8",
        "name": "RGPU-95",
        "category": "Cognitive & Neurological",
        "mechanism": "Peptide modulator of glutamate receptors reducing excitotoxicity",
        "focus": "neuroinflammation management",
        "benefits": [
            "Stabilizes cognitive performance under fatigue",
            "Reduces oxidative stress",
            "Supports neurovascular integrity",
        ],
        "loading": "500 mcg IV weekly for 6 weeks",
        "maintenance": "500 mcg biweekly",
        "timing": "Administer under medical supervision",
        "notes": "Ensure antioxidant support during cycles.",
    },
    {
        "id": "neuro-9",
        "name": "DSIP (Delta Sleep Inducing Peptide)",
        "category": "Cognitive & Neurological",
        "mechanism": "Neuropeptide promoting slow-wave sleep and stress adaptation",
        "focus": "deep sleep restoration",
        "benefits": [
            "Improves sleep architecture",
            "Supports stress hormone balance",
            "Enhances recovery during overreaching phases",
        ],
        "loading": "100 mcg nightly for 20 days",
        "maintenance": "100 mcg as needed",
        "timing": "30 minutes before bed",
        "notes": "Avoid combining with sedatives without oversight.",
    },
    {
        "id": "neuro-10",
        "name": "Epithalon",
        "category": "Cognitive & Neurological",
        "mechanism": "Pineal peptide regulating telomerase and circadian rhythms",
        "focus": "sleep and longevity support",
        "benefits": [
            "Improves circadian entrainment",
            "Supports immune balance",
            "May enhance cognitive clarity in aging",
        ],
        "loading": "10 mg IM daily for 20 days",
        "maintenance": "10 mg monthly",
        "timing": "Evening",
        "notes": "Often cycled twice yearly in longevity protocols.",
    },
    {
        "id": "imm-1",
        "name": "Thymosin Alpha-1",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Thymic peptide restoring T-cell function and modulating cytokines",
        "focus": "immune resilience",
        "benefits": [
            "Enhances T-cell maturation",
            "Balances Th1/Th2 immune response",
            "Supports recovery from viral illnesses",
        ],
        "loading": "1.6 mg twice weekly for 12 weeks",
        "maintenance": "1.6 mg weekly",
        "timing": "Morning with immune support stack",
        "notes": "Pair with vitamin D optimization for synergistic effects.",
    },
    {
        "id": "imm-2",
        "name": "Thymosin Beta-4",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Peptide that modulates actin and reduces inflammation",
        "focus": "systemic inflammation control",
        "benefits": [
            "Accelerates wound healing",
            "Reduces inflammatory cytokines",
            "Supports cardiovascular tissue repair",
        ],
        "loading": "2 mg twice weekly for 6 weeks",
        "maintenance": "2 mg monthly",
        "timing": "Morning or evening",
        "notes": "Combine with omega-3 fatty acids for inflammation control.",
    },
    {
        "id": "imm-3",
        "name": "LL-37",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Cathelicidin antimicrobial peptide modulating innate immunity",
        "focus": "immune defense and biofilm disruption",
        "benefits": [
            "Active against broad-spectrum pathogens",
            "Supports wound healing",
            "Helps break down biofilms",
        ],
        "loading": "100 mcg daily for 14 days",
        "maintenance": "100 mcg twice weekly",
        "timing": "Morning on empty stomach",
        "notes": "Monitor for herx reactions; ramp slowly.",
    },
    {
        "id": "imm-4",
        "name": "KPV",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Alpha-MSH fragment reducing NF-kB activation",
        "focus": "gut and skin inflammation control",
        "benefits": [
            "Supports gut barrier integrity",
            "Reduces dermatologic inflammation",
            "Pairs with BPC-157 for GI protocols",
        ],
        "loading": "500 mcg daily for 8 weeks",
        "maintenance": "250 mcg daily",
        "timing": "Morning or split doses",
        "notes": "Topical formulations can complement injections for skin.",
    },
    {
        "id": "imm-5",
        "name": "VIP (Vasoactive Intestinal Peptide)",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Neuropeptide balancing cytokines and supporting vasodilation",
        "focus": "chronic inflammatory response syndrome support",
        "benefits": [
            "Improves oxygenation",
            "Reduces inflammatory markers",
            "Supports cognitive clarity in CIRS",
        ],
        "loading": "50 mcg intranasal four times daily for 4 weeks",
        "maintenance": "50 mcg twice daily",
        "timing": "Evenly spaced throughout day",
        "notes": "Screen for mold exposure resolution before initiating.",
    },
    {
        "id": "imm-6",
        "name": "Thymulin",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Zinc-bound thymic peptide modulating immune maturation",
        "focus": "immune rebalancing",
        "benefits": [
            "Supports antibody production",
            "Enhances vaccine responsiveness",
            "Modulates allergic responses",
        ],
        "loading": "10 mg weekly for 6 weeks",
        "maintenance": "10 mg monthly",
        "timing": "Morning",
        "notes": "Ensure adequate zinc status for optimal activity.",
    },
    {
        "id": "imm-7",
        "name": "Alpha-Defensin Boost",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Peptide blend enhancing antimicrobial defensin production",
        "focus": "innate immune priming",
        "benefits": [
            "Improves mucosal immunity",
            "Combats recurrent infections",
            "Supports microbiome balance",
        ],
        "loading": "200 mcg daily for 21 days",
        "maintenance": "200 mcg twice weekly",
        "timing": "Morning",
        "notes": "Rotate with probiotics to support healthy flora.",
    },
    {
        "id": "imm-8",
        "name": "BAM-15 Peptide",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Modulates mitochondrial uncoupling and inflammatory cascades",
        "focus": "metabolic inflammation reduction",
        "benefits": [
            "Reduces inflammatory adipokines",
            "Supports metabolic flexibility",
            "Improves energy during chronic illness recovery",
        ],
        "loading": "10 mg oral daily for 6 weeks",
        "maintenance": "5 mg daily",
        "timing": "Morning with meal",
        "notes": "Hydration is key due to thermogenic effect.",
    },
    {
        "id": "imm-9",
        "name": "ARA-290",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Innate repair receptor agonist reducing neuropathic pain and inflammation",
        "focus": "neuropathic inflammation relief",
        "benefits": [
            "Improves microvascular blood flow",
            "Reduces small fiber neuropathy symptoms",
            "Supports renal protection",
        ],
        "loading": "2 mg subcutaneous daily for 28 days",
        "maintenance": "2 mg twice weekly",
        "timing": "Morning",
        "notes": "Coordinate with neurologist for chronic neuropathy management.",
    },
    {
        "id": "imm-10",
        "name": "Beta-Defensin 2",
        "category": "Immune & Inflammatory Modulation",
        "mechanism": "Antimicrobial peptide that also modulates adaptive immunity",
        "focus": "barrier defense",
        "benefits": [
            "Supports skin and mucosal immunity",
            "Balances microbiome composition",
            "Assists wound repair",
        ],
        "loading": "100 mcg daily for 3 weeks",
        "maintenance": "100 mcg twice weekly",
        "timing": "Morning or evening",
        "notes": "Great adjunct to dermatologic protocols for chronic lesions.",
    },
    {
        "id": "sex-1",
        "name": "PT-141",
        "category": "Sexual Health & Vitality",
        "mechanism": "Melanocortin agonist increasing sexual desire and arousal",
        "focus": "on-demand libido support",
        "benefits": [
            "Improves arousal in both men and women",
            "Bypasses nitric oxide pathways",
            "Supports confidence and mood",
        ],
        "loading": "1.75 mg SC 45 minutes before intimacy",
        "maintenance": "1.25 mg as needed",
        "timing": "30-60 minutes prior to activity",
        "notes": "Educate on potential flushing or nausea.",
    },
    {
        "id": "sex-2",
        "name": "Kisspeptin-10",
        "category": "Sexual Health & Vitality",
        "mechanism": "Stimulates GnRH release supporting sex hormone production",
        "focus": "fertility and hormonal rejuvenation",
        "benefits": [
            "Supports LH/FSH release",
            "Improves sperm parameters",
            "May support menstrual regularity",
        ],
        "loading": "100 mcg daily for 4 weeks",
        "maintenance": "100 mcg twice weekly",
        "timing": "Morning",
        "notes": "Monitor reproductive hormone labs when stacking with HCG.",
    },
    {
        "id": "sex-3",
        "name": "Oxytocin Microdose",
        "category": "Sexual Health & Vitality",
        "mechanism": "Peptide hormone enhancing bonding, trust, and orgasmic response",
        "focus": "intimacy enhancement",
        "benefits": [
            "Enhances emotional connection",
            "Supports sexual satisfaction",
            "Reduces stress during intimacy",
        ],
        "loading": "24 IU intranasal prior to encounters",
        "maintenance": "12-24 IU as desired",
        "timing": "15-20 minutes before intimacy",
        "notes": "Use sparingly to prevent receptor downregulation.",
    },
    {
        "id": "sex-4",
        "name": "Bremelanotide Daily",
        "category": "Sexual Health & Vitality",
        "mechanism": "Melanocortin agonist optimized for daily microdosing",
        "focus": "libido maintenance",
        "benefits": [
            "Supports consistent sexual desire",
            "Improves arousal confidence",
            "Helpful in antidepressant-induced dysfunction",
        ],
        "loading": "500 mcg daily for 14 days",
        "maintenance": "250 mcg daily",
        "timing": "Evening",
        "notes": "Assess blood pressure before initiating due to vasoconstriction potential.",
    },
    {
        "id": "sex-5",
        "name": "Melanotan I",
        "category": "Sexual Health & Vitality",
        "mechanism": "Alpha-MSH analog improving pigmentation and libido",
        "focus": "gradual libido & skin tone enhancement",
        "benefits": [
            "Provides mild libido support",
            "Enhances sun resistance",
            "Supports mood and confidence",
        ],
        "loading": "500 mcg daily for 10 days",
        "maintenance": "500 mcg twice weekly",
        "timing": "Evening",
        "notes": "Monitor for freckles or nevi darkening.",
    },
    {
        "id": "sex-6",
        "name": "Vasoactive Intestinal Peptide (VIP) Spray",
        "category": "Sexual Health & Vitality",
        "mechanism": "Enhances blood flow and relaxation of smooth muscle",
        "focus": "vascular erectile support",
        "benefits": [
            "Improves erectile response",
            "Reduces performance anxiety",
            "Supports endothelial health",
        ],
        "loading": "2 sprays intranasal as needed",
        "maintenance": "1-2 sprays as required",
        "timing": "15 minutes before activity",
        "notes": "Store refrigerated and allow to reach room temp before use.",
    },
    {
        "id": "sex-7",
        "name": "Pinealon",
        "category": "Sexual Health & Vitality",
        "mechanism": "Pineal peptide complex supporting circadian-driven hormone release",
        "focus": "hormonal harmony",
        "benefits": [
            "Improves sleep-driven hormone rhythms",
            "Supports libido through melatonin balance",
            "Enhances overall vitality",
        ],
        "loading": "10 mg orally nightly for 20 days",
        "maintenance": "10 mg weekly",
        "timing": "Evening before bed",
        "notes": "Combine with stress management practices.",
    },
    {
        "id": "sex-8",
        "name": "HCG Microdose",
        "category": "Sexual Health & Vitality",
        "mechanism": "Stimulates Leydig cells to maintain testosterone production",
        "focus": "male fertility and libido preservation",
        "benefits": [
            "Maintains testicular volume during TRT",
            "Supports progesterone in women",
            "Enhances mood and libido",
        ],
        "loading": "500 IU twice weekly for 4 weeks",
        "maintenance": "250 IU twice weekly",
        "timing": "Morning",
        "notes": "Monitor estradiol levels during combined therapy.",
    },
    {
        "id": "sex-9",
        "name": "FSH Stim Peptide",
        "category": "Sexual Health & Vitality",
        "mechanism": "Peptide analog that promotes follicle stimulating hormone release",
        "focus": "ovarian and testicular support",
        "benefits": [
            "Supports follicular development",
            "Improves sperm maturation",
            "Useful in fertility preservation protocols",
        ],
        "loading": "100 mcg daily for 21 days",
        "maintenance": "Cycle per fertility specialist guidance",
        "timing": "Morning",
        "notes": "Coordinate with reproductive endocrinologist for dosing windows.",
    },
    {
        "id": "sex-10",
        "name": "LIV-100 Peptide",
        "category": "Sexual Health & Vitality",
        "mechanism": "Endothelial nitric oxide modulator improving pelvic blood flow",
        "focus": "libido and erectile quality",
        "benefits": [
            "Enhances genital blood flow",
            "Supports stamina and energy",
            "Complements lifestyle interventions",
        ],
        "loading": "5 mg sublingual daily for 8 weeks",
        "maintenance": "5 mg before intimacy",
        "timing": "30 minutes prior to activity",
        "notes": "Caution with nitrate medications; monitor blood pressure.",
    },
    {
        "id": "derm-1",
        "name": "GHK-Cu Topical",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Copper peptide stimulating collagen and elastin",
        "focus": "skin rejuvenation",
        "benefits": [
            "Reduces fine lines",
            "Improves hair density",
            "Accelerates wound healing",
        ],
        "loading": "Apply 2-3 drops twice daily",
        "maintenance": "Daily evening application",
        "timing": "Morning and night",
        "notes": "Avoid simultaneous vitamin C application to preserve copper."
    },
    {
        "id": "derm-2",
        "name": "Argireline",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "SNAP-25 analog reducing facial muscle contraction",
        "focus": "expression line softening",
        "benefits": [
            "Smooths dynamic wrinkles",
            "Non-invasive alternative to neuromodulators",
            "Pairs with hyaluronic acid serums",
        ],
        "loading": "Apply 2x daily to expression lines",
        "maintenance": "Once daily after improvements",
        "timing": "Morning and evening",
        "notes": "Consistent use required for visible results.",
    },
    {
        "id": "derm-3",
        "name": "Matrixyl 3000",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Palmitoyl tetrapeptide blend stimulating extracellular matrix",
        "focus": "collagen remodeling",
        "benefits": [
            "Improves firmness",
            "Reduces wrinkle depth",
            "Enhances moisture retention",
        ],
        "loading": "Apply pea-sized amount twice daily",
        "maintenance": "Daily evening use",
        "timing": "Morning and night",
        "notes": "Combine with sunscreen during day for best outcome.",
    },
    {
        "id": "derm-4",
        "name": "Syn-Coll",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Palmitoyl tripeptide-5 stimulating TGF-β pathways",
        "focus": "firmness and elasticity",
        "benefits": [
            "Stimulates collagen synthesis",
            "Reduces wrinkle volume",
            "Supports scar remodeling",
        ],
        "loading": "Use twice daily for 8 weeks",
        "maintenance": "Once daily",
        "timing": "Morning or evening",
        "notes": "Layer under moisturizer for optimal absorption.",
    },
    {
        "id": "derm-5",
        "name": "Snap-8",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Octapeptide reducing catecholamine release at neuromuscular junction",
        "focus": "fine line relaxation",
        "benefits": [
            "Softens crow's feet",
            "Complements botulinum toxin",
            "Hydrates skin surface",
        ],
        "loading": "Apply small amount twice daily",
        "maintenance": "Daily",
        "timing": "Morning and night",
        "notes": "Combine with peptides that boost collagen for synergy.",
    },
    {
        "id": "derm-6",
        "name": "GHK-Cu Microneedling Serum",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Copper peptide delivered via microneedling for enhanced penetration",
        "focus": "intensive skin remodeling",
        "benefits": [
            "Improves scar appearance",
            "Stimulates hair follicles",
            "Brightens complexion",
        ],
        "loading": "Apply post-needling weekly",
        "maintenance": "Use post-procedure",
        "timing": "Evening after microneedling",
        "notes": "Ensure sterile technique to prevent infection.",
    },
    {
        "id": "derm-7",
        "name": "Eyelash Peptide Complex",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Myristoyl pentapeptides stimulating lash growth",
        "focus": "lash density",
        "benefits": [
            "Thickens lashes",
            "Supports eyelash length",
            "Conditions lash line",
        ],
        "loading": "Apply nightly to lash line",
        "maintenance": "3-4x weekly",
        "timing": "Evening",
        "notes": "Avoid contact with eyes; use clean applicator.",
    },
    {
        "id": "derm-8",
        "name": "Copper Tripeptide Mask",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Sheet mask delivering copper peptides for hydration and repair",
        "focus": "post-procedure recovery",
        "benefits": [
            "Calms redness",
            "Accelerates healing",
            "Boosts hydration",
        ],
        "loading": "Apply 2-3 times weekly",
        "maintenance": "Weekly",
        "timing": "Evening or post-treatment",
        "notes": "Store chilled for soothing effect.",
    },
    {
        "id": "derm-9",
        "name": "Body Firming Peptide Lotion",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Tetrapeptide complex supporting elastin and collagen in body skin",
        "focus": "body contour maintenance",
        "benefits": [
            "Improves skin tone",
            "Reduces appearance of cellulite",
            "Enhances hydration",
        ],
        "loading": "Apply twice daily to target areas",
        "maintenance": "Daily",
        "timing": "Morning and evening",
        "notes": "Combine with dry brushing for enhanced circulation.",
    },
    {
        "id": "derm-10",
        "name": "Neck & Décolletage Peptide",
        "category": "Dermal & Aesthetic Support",
        "mechanism": "Palmitoyl tripeptide blend improving thin skin resiliency",
        "focus": "neck rejuvenation",
        "benefits": [
            "Smooths crepey skin",
            "Improves firmness",
            "Provides antioxidant protection",
        ],
        "loading": "Apply nightly for 8 weeks",
        "maintenance": "Every other night",
        "timing": "Evening",
        "notes": "Layer over hydrating serum to lock in moisture.",
    },
    {
        "id": "cardio-1",
        "name": "Angiotensin (1-7)",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Peptide counteracting angiotensin II to promote vasodilation",
        "focus": "blood pressure modulation",
        "benefits": [
            "Supports endothelial nitric oxide",
            "Improves insulin sensitivity",
            "Reduces vascular inflammation",
        ],
        "loading": "400 mcg daily for 6 weeks",
        "maintenance": "200 mcg daily",
        "timing": "Morning",
        "notes": "Monitor blood pressure and electrolytes.",
    },
    {
        "id": "cardio-2",
        "name": "BPC-157 Cardio",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Cardiac-focused formulation supporting endothelial repair",
        "focus": "vascular healing",
        "benefits": [
            "Improves microcirculation",
            "Reduces arterial inflammation",
            "Supports post-angioplasty recovery",
        ],
        "loading": "500 mcg daily for 6 weeks",
        "maintenance": "250 mcg daily",
        "timing": "Morning",
        "notes": "Use alongside cardiologist-directed therapy.",
    },
    {
        "id": "cardio-3",
        "name": "Lisinopril Peptide Enhancer",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Peptide augmenting ACE inhibitor response",
        "focus": "blood pressure optimization",
        "benefits": [
            "Allows lower ACE inhibitor dosing",
            "Improves endothelial function",
            "Reduces vascular stiffness",
        ],
        "loading": "2 mg daily for 8 weeks",
        "maintenance": "1 mg daily",
        "timing": "Morning",
        "notes": "Monitor kidney function and potassium.",
    },
    {
        "id": "cardio-4",
        "name": "GLP-1 Cardioprotective",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Incretin analog with specific cardiovascular outcome data",
        "focus": "cardiometabolic risk reduction",
        "benefits": [
            "Reduces major adverse cardiac events",
            "Improves weight and glycemic control",
            "Lowers blood pressure modestly",
        ],
        "loading": "0.5 mg weekly for 4 weeks",
        "maintenance": "1 mg weekly",
        "timing": "Consistent weekly schedule",
        "notes": "Assess for GI tolerance and titrate gradually.",
    },
    {
        "id": "cardio-5",
        "name": "Thymosin Beta-4 Cardio",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Cardiac remodeling support via actin regulation",
        "focus": "post-injury cardiac repair",
        "benefits": [
            "Supports angiogenesis in cardiac tissue",
            "Reduces fibrotic scarring",
            "Improves exercise tolerance",
        ],
        "loading": "4 mg weekly for 4 weeks",
        "maintenance": "2 mg weekly",
        "timing": "Morning",
        "notes": "Coordinate with cardiology for integration with rehab.",
    },
    {
        "id": "cardio-6",
        "name": "BNP Mimetic",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "B-type natriuretic peptide analog aiding natriuresis and vasodilation",
        "focus": "fluid balance and blood pressure control",
        "benefits": [
            "Reduces blood pressure",
            "Supports kidney perfusion",
            "Improves heart failure symptoms",
        ],
        "loading": "10 mcg IV weekly for 4 weeks",
        "maintenance": "10 mcg biweekly",
        "timing": "Administer in clinical setting",
        "notes": "Monitor blood pressure closely during infusion.",
    },
    {
        "id": "cardio-7",
        "name": "Adiponectin Modulator",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Peptide increasing adiponectin to improve lipid metabolism",
        "focus": "lipid profile optimization",
        "benefits": [
            "Raises HDL cholesterol",
            "Reduces triglycerides",
            "Supports insulin sensitivity",
        ],
        "loading": "5 mg oral daily for 12 weeks",
        "maintenance": "2.5 mg daily",
        "timing": "Morning with breakfast",
        "notes": "Reassess lipid panel every 8-12 weeks.",
    },
    {
        "id": "cardio-8",
        "name": "Elabela",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Apelin receptor agonist enhancing cardiac output",
        "focus": "cardiac performance",
        "benefits": [
            "Supports endothelial integrity",
            "Improves diastolic function",
            "Assists in blood pressure regulation",
        ],
        "loading": "2 mg subcutaneous daily for 6 weeks",
        "maintenance": "2 mg three times weekly",
        "timing": "Morning",
        "notes": "Monitor for hypotension in sensitive individuals.",
    },
    {
        "id": "cardio-9",
        "name": "Apelin-13",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Peptide improving cardiac contractility and vascular tone",
        "focus": "exercise tolerance",
        "benefits": [
            "Improves cardiac output during exercise",
            "Reduces blood pressure",
            "Enhances glucose uptake",
        ],
        "loading": "500 mcg pre-workout for 6 weeks",
        "maintenance": "500 mcg 3x weekly",
        "timing": "30 minutes before training",
        "notes": "Coordinate with cardiometabolic monitoring program.",
    },
    {
        "id": "cardio-10",
        "name": "VasoRelax Blend",
        "category": "Cardiometabolic & Vascular",
        "mechanism": "Blend of vasoactive peptides to improve endothelial-dependent relaxation",
        "focus": "vascular flexibility",
        "benefits": [
            "Reduces arterial stiffness",
            "Supports nitric oxide production",
            "Enhances exercise performance",
        ],
        "loading": "1 mL IV weekly for 6 weeks",
        "maintenance": "1 mL biweekly",
        "timing": "Administer during supervised therapy",
        "notes": "Monitor blood pressure and electrolytes.",
    },
    {
        "id": "gi-1",
        "name": "BPC-157 Oral",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Gastroprotective peptide supporting mucosal healing",
        "focus": "gut lining repair",
        "benefits": [
            "Improves intestinal permeability",
            "Reduces gastric inflammation",
            "Supports microbiome balance",
        ],
        "loading": "500 mcg oral daily for 6 weeks",
        "maintenance": "250 mcg daily",
        "timing": "Morning on empty stomach",
        "notes": "Combine with elimination diet for best outcomes.",
    },
    {
        "id": "gi-2",
        "name": "KPV Oral",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Alpha-MSH fragment calming gut inflammation",
        "focus": "IBD symptom control",
        "benefits": [
            "Reduces inflammatory cytokines",
            "Supports mucosal healing",
            "Improves GI comfort",
        ],
        "loading": "500 mcg oral daily for 8 weeks",
        "maintenance": "250 mcg daily",
        "timing": "Morning",
        "notes": "Synergistic with probiotics and glutamine.",
    },
    {
        "id": "gi-3",
        "name": "LL-37 Oral",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Antimicrobial peptide targeting gut dysbiosis",
        "focus": "microbiome recalibration",
        "benefits": [
            "Breaks down biofilms",
            "Reduces pathogenic bacteria",
            "Supports immune balance",
        ],
        "loading": "100 mcg oral daily for 3 weeks",
        "maintenance": "Cycle as needed",
        "timing": "Morning away from meals",
        "notes": "Use alongside binders to manage die-off reactions.",
    },
    {
        "id": "gi-4",
        "name": "Intestinal Repair Complex",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Blend of glutamine-rich peptides reinforcing tight junctions",
        "focus": "leaky gut repair",
        "benefits": [
            "Supports mucosal regeneration",
            "Improves nutrient absorption",
            "Reduces GI discomfort",
        ],
        "loading": "10 g powder daily for 8 weeks",
        "maintenance": "5 g daily",
        "timing": "Morning shake",
        "notes": "Combine with anti-inflammatory diet for sustained progress.",
    },
    {
        "id": "gi-5",
        "name": "Larazotide Acetate",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Zonulin antagonist tightening intestinal junctions",
        "focus": "gluten sensitivity management",
        "benefits": [
            "Reduces zonulin spikes",
            "Supports celiac disease protocols",
            "Improves GI symptoms after gluten exposure",
        ],
        "loading": "0.5 mg three times daily for 12 weeks",
        "maintenance": "0.5 mg twice daily",
        "timing": "Before meals",
        "notes": "Continue gluten-free diet for best results.",
    },
    {
        "id": "gi-6",
        "name": "Gut Motility Peptide",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Prokinetic peptide supporting migrating motor complex",
        "focus": "motility normalization",
        "benefits": [
            "Reduces bloating",
            "Improves regularity",
            "Supports SIBO protocols",
        ],
        "loading": "100 mcg before bed for 12 weeks",
        "maintenance": "100 mcg nightly",
        "timing": "Evening on empty stomach",
        "notes": "Pair with antimicrobial protocols when addressing SIBO.",
    },
    {
        "id": "gi-7",
        "name": "Secretin Microdose",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Peptide stimulating pancreatic bicarbonate and enzyme flow",
        "focus": "digestive enzyme support",
        "benefits": [
            "Improves pancreatic output",
            "Reduces post-meal discomfort",
            "Supports bile flow",
        ],
        "loading": "50 mcg SC pre-meal for 4 weeks",
        "maintenance": "50 mcg before largest meal",
        "timing": "10 minutes before meals",
        "notes": "Coordinate with functional GI lab testing for personalization.",
    },
    {
        "id": "gi-8",
        "name": "Zonulin Balance Peptide",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Peptide complex stabilizing tight junction proteins",
        "focus": "intestinal permeability support",
        "benefits": [
            "Decreases food sensitivity reactions",
            "Supports autoimmune calming",
            "Improves nutrient assimilation",
        ],
        "loading": "1 mg oral daily for 8 weeks",
        "maintenance": "1 mg every other day",
        "timing": "Morning",
        "notes": "Pair with elimination reintroduction protocols.",
    },
    {
        "id": "gi-9",
        "name": "Short Chain Peptide Butyrate",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Peptide-bound butyrate delivering colonocyte fuel",
        "focus": "colon health",
        "benefits": [
            "Feeds beneficial bacteria",
            "Reduces gut inflammation",
            "Improves stool form",
        ],
        "loading": "600 mg oral daily for 6 weeks",
        "maintenance": "300 mg daily",
        "timing": "With evening meal",
        "notes": "Combine with fiber diversity goals.",
    },
    {
        "id": "gi-10",
        "name": "Tripeptide Tight Junction Spray",
        "category": "Gastrointestinal & Barrier Integrity",
        "mechanism": "Nasal spray delivering peptides that signal gut-brain barrier repair",
        "focus": "neuro-gut access support",
        "benefits": [
            "Calms neuroinflammation from gut triggers",
            "Improves vagal tone",
            "Supports mood regulation",
        ],
        "loading": "2 sprays per nostril twice daily for 6 weeks",
        "maintenance": "2 sprays daily",
        "timing": "Morning and evening",
        "notes": "Encourage diaphragmatic breathing to complement vagal support.",
    },
    {
        "id": "lon-1",
        "name": "Epitalon",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Tetrapeptide regulating telomerase activity and circadian rhythm",
        "focus": "telomere support and sleep quality",
        "benefits": [
            "Normalizes melatonin secretion",
            "Supports immune surveillance",
            "May lengthen telomeres over repeated cycles",
        ],
        "loading": "10 mg nightly for 20 days",
        "maintenance": "10 mg monthly",
        "timing": "Evening",
        "notes": "Cycle twice per year for cumulative benefits.",
    },
    {
        "id": "lon-2",
        "name": "Thymus Peptide Complex",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Peptide complex rejuvenating thymic output",
        "focus": "immune age reversal",
        "benefits": [
            "Improves adaptive immune balance",
            "Supports healthy inflammatory response",
            "May enhance vaccine response in older adults",
        ],
        "loading": "10 mg IM twice weekly for 6 weeks",
        "maintenance": "10 mg monthly",
        "timing": "Morning",
        "notes": "Pair with micronutrient optimization for thymic support.",
    },
    {
        "id": "lon-3",
        "name": "Foxo4-DRI",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Peptide that disrupts p53-Foxo4 interaction to clear senescent cells",
        "focus": "senolytic cycling",
        "benefits": [
            "Reduces senescence-associated secretory phenotype",
            "Improves tissue regenerative capacity",
            "Supports joint comfort",
        ],
        "loading": "5 mg IV weekly for 3 weeks",
        "maintenance": "Cycle every 6 months",
        "timing": "Administer in clinical setting",
        "notes": "Medical oversight required due to potent senolytic action.",
    },
    {
        "id": "lon-4",
        "name": "Humanin",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Mitochondrial derived peptide protecting against oxidative stress",
        "focus": "cellular resilience",
        "benefits": [
            "Improves insulin sensitivity",
            "Protects neurons and cardiomyocytes",
            "Supports metabolic flexibility",
        ],
        "loading": "12 mg weekly for 6 weeks",
        "maintenance": "12 mg biweekly",
        "timing": "Morning",
        "notes": "Combine with exercise and fasting mimetics for synergy.",
    },
    {
        "id": "lon-5",
        "name": "SS-31 (Elamipretide)",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Mitochondria-targeted peptide stabilizing cardiolipin",
        "focus": "mitochondrial rejuvenation",
        "benefits": [
            "Improves mitochondrial ATP production",
            "Reduces oxidative damage",
            "Supports cardiac and muscular endurance",
        ],
        "loading": "0.5 mg/kg IV twice weekly for 4 weeks",
        "maintenance": "10 mg SC daily",
        "timing": "Morning",
        "notes": "Hydration and electrolyte balance support mitochondrial performance.",
    },
    {
        "id": "lon-6",
        "name": "Pinealon",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Pineal peptide regulating neuroendocrine aging",
        "focus": "neuroendocrine rejuvenation",
        "benefits": [
            "Supports cognitive clarity",
            "Normalizes circadian rhythms",
            "Improves stress resilience",
        ],
        "loading": "10 mg nightly for 20 days",
        "maintenance": "10 mg weekly",
        "timing": "Evening",
        "notes": "Stacks well with Epitalon for pineal rejuvenation.",
    },
    {
        "id": "lon-7",
        "name": "GDF11 Peptide",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Peptide restoring youthful signaling in neural and vascular tissues",
        "focus": "systemic rejuvenation",
        "benefits": [
            "Enhances neurogenesis",
            "Improves vascular elasticity",
            "Supports muscle stem cell function",
        ],
        "loading": "0.1 mg IV weekly for 4 weeks",
        "maintenance": "0.1 mg monthly",
        "timing": "Administer with clinician oversight",
        "notes": "Track hematocrit and blood pressure during cycles.",
    },
    {
        "id": "lon-8",
        "name": "Klotho Stimulating Peptide",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Peptide blend upregulating klotho expression",
        "focus": "renal and cognitive longevity",
        "benefits": [
            "Supports kidney filtration",
            "Improves cognitive resilience",
            "Balances mineral metabolism",
        ],
        "loading": "1 mg SC three times weekly for 8 weeks",
        "maintenance": "1 mg weekly",
        "timing": "Morning",
        "notes": "Monitor phosphate and calcium levels periodically.",
    },
    {
        "id": "lon-9",
        "name": "NAD+ Peptide Catalyst",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Peptide complex enhancing NAD+ salvage pathway",
        "focus": "cellular energy support",
        "benefits": [
            "Boosts sirtuin activity",
            "Improves mitochondrial biogenesis",
            "Supports metabolic health",
        ],
        "loading": "1 mL IM twice weekly for 6 weeks",
        "maintenance": "1 mL weekly",
        "timing": "Morning",
        "notes": "Pair with oral NAD+ precursors for comprehensive support.",
    },
    {
        "id": "lon-10",
        "name": "Thymulin Longevity",
        "category": "Longevity & Cellular Optimization",
        "mechanism": "Zinc-thymulin complex supporting thymic and neuroendocrine balance",
        "focus": "immune and hormonal rejuvenation",
        "benefits": [
            "Supports thymic hormone output",
            "Improves sleep quality",
            "Enhances immune surveillance",
        ],
        "loading": "10 mg weekly for 6 weeks",
        "maintenance": "10 mg monthly",
        "timing": "Evening",
        "notes": "Ensure zinc sufficiency; avoid concurrent high-dose iron.",
    },
]

stack_protocols = [
    {
        "id": "stack-gh-synergy",
        "name": "GH Pulse Synergy",
        "goal": "Increase growth hormone signaling for lean mass and recovery",
        "overview": "Pairs long-acting CJC-1295 with fast-acting ipamorelin and tissue-healing BPC-157 to mimic physiologic GH pulses while accelerating recovery.",
        "peptides": [
            {"name": "CJC-1295 w/ DAC", "dose": "2 mg once weekly", "timing": "Sunday 21:00"},
            {"name": "Ipamorelin", "dose": "300 mcg nightly", "timing": "Daily 21:30 on empty stomach"},
            {"name": "BPC-157", "dose": "250 mcg twice daily", "timing": "Morning & evening near injury"}
        ],
        "schedule": [
            {"day": "Daily", "instructions": "Morning: Administer 250 mcg BPC-157 near injury site."},
            {"day": "Daily", "instructions": "Evening: Take BPC-157 and 300 mcg ipamorelin 30 minutes before bed."},
            {"day": "Sunday", "instructions": "Pin 2 mg CJC-1295 w/ DAC in the evening after shower."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 3.0,
            "instructions": "Reconstitute each peptide individually with bacteriostatic water (2 mL for CJC-1295, 2 mL for ipamorelin, 1 mL for BPC-157). Label vials with concentration and store refrigerated."
        },
        "notes": [
            "Perform GH labs (IGF-1) after 8 weeks to fine-tune dosing.",
            "Avoid carbohydrate-heavy meals within 2 hours of nighttime peptides.",
            "Include deload weeks every 12 weeks."
        ]
    },
    {
        "id": "stack-metabolic-reset",
        "name": "Metabolic Reset Phase",
        "goal": "Improve insulin sensitivity and fat loss while protecting lean mass",
        "overview": "Combines MOTS-c for mitochondrial drive with GLP-1 appetite control and AOD 9604 for localized lipolysis.",
        "peptides": [
            {"name": "MOTS-c", "dose": "10 mg weekly", "timing": "Monday 07:00"},
            {"name": "GLP-1 Analog Peptide", "dose": "0.5-1 mg weekly", "timing": "Thursday 08:00"},
            {"name": "AOD 9604", "dose": "300 mcg daily", "timing": "Daily fasted"}
        ],
        "schedule": [
            {"day": "Monday", "instructions": "Inject MOTS-c prior to cardio session."},
            {"day": "Thursday", "instructions": "Administer GLP-1 analog and monitor hydration."},
            {"day": "Daily", "instructions": "Take AOD 9604 each morning before breakfast; add a second 150 mcg pre-walk if plateaus."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 2.5,
            "instructions": "Mix each lyophilized vial with 2 mL of bacteriostatic water. GLP-1 analogs may require gentle rolling to dissolve." 
        },
        "notes": [
            "Follow a slight caloric deficit (10-15%).",
            "Increase protein to 1 g per lb lean mass for lean tissue retention.",
            "Deload GLP-1 analog after 16 weeks to reassess hunger cues."
        ]
    },
    {
        "id": "stack-cognitive-clarity",
        "name": "Cognitive Clarity Stack",
        "goal": "Enhance focus, stress resilience, and long-term neuroplasticity",
        "overview": "Uses Semax and Selank intranasally for daily focus with Dihexa providing long-range synaptic support.",
        "peptides": [
            {"name": "Semax", "dose": "300 mcg", "timing": "Morning & midday"},
            {"name": "Selank", "dose": "300 mcg", "timing": "Morning & afternoon"},
            {"name": "Dihexa", "dose": "10 mg", "timing": "Morning oral"}
        ],
        "schedule": [
            {"day": "Weekdays", "instructions": "Semax 300 mcg per nostril AM & lunch; Selank 300 mcg AM & mid-afternoon."},
            {"day": "Daily", "instructions": "Take 10 mg Dihexa with breakfast; cycle 5 days on, 2 days off."},
            {"day": "Weekend", "instructions": "Reduce to once-daily Semax/Selank or pause for receptor reset."}
        ],
        "reconstitution": {
            "diluent": "Sterile saline",
            "volume_ml": 2.0,
            "instructions": "Reconstitute Semax and Selank with 2 mL sterile saline into nasal spray bottles; store refrigerated for 30 days." 
        },
        "notes": [
            "Hydrate and include omega-3 fatty acids to support neuroplasticity.",
            "Avoid dosing after 4 PM to protect sleep.",
            "Track subjective cognitive scores weekly."
        ]
    },
    {
        "id": "stack-immune-armor",
        "name": "Immune Armor Protocol",
        "goal": "Strengthen innate and adaptive immunity during high-stress seasons",
        "overview": "Thymosin Alpha-1 leads adaptive support while KPV and Thymulin modulate inflammation and antibody balance.",
        "peptides": [
            {"name": "Thymosin Alpha-1", "dose": "1.6 mg", "timing": "Monday & Thursday mornings"},
            {"name": "KPV", "dose": "250 mcg", "timing": "Daily morning"},
            {"name": "Thymulin", "dose": "10 mg", "timing": "Saturday morning"}
        ],
        "schedule": [
            {"day": "Mon/Thu", "instructions": "Administer Thymosin Alpha-1 subcutaneously."},
            {"day": "Daily", "instructions": "Take KPV each morning before breakfast."},
            {"day": "Saturday", "instructions": "Dose Thymulin to reinforce thymic signaling; follow with light activity."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 2.0,
            "instructions": "Reconstitute each peptide with 2 mL bacteriostatic water; label syringes with day-specific dosing." 
        },
        "notes": [
            "Add vitamin D3, zinc, and sleep hygiene for full immune program.",
            "Discontinue during acute fever unless clinician approves.",
            "Reassess inflammatory markers after 8 weeks."
        ]
    },
    {
        "id": "stack-sexual-vitality",
        "name": "Sexual Vitality Duo",
        "goal": "Boost desire, connection, and erectile quality",
        "overview": "Combines fast-acting PT-141 with oxytocin microdosing for intimacy and mood support.",
        "peptides": [
            {"name": "PT-141", "dose": "1.75 mg", "timing": "As needed 45 minutes pre-activity"},
            {"name": "Oxytocin Microdose", "dose": "24 IU", "timing": "15 minutes pre-activity"}
        ],
        "schedule": [
            {"day": "Encounter Days", "instructions": "Reconstitute and pre-load syringes for PT-141; store in travel case."},
            {"day": "Encounter Days", "instructions": "Administer oxytocin spray shortly before intimacy to reinforce bonding."},
            {"day": "Weekly", "instructions": "Limit PT-141 to 3 uses per week to avoid tolerance."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 1.5,
            "instructions": "Mix PT-141 with 1 mL bacteriostatic water; oxytocin typically ships premixed but can be reconstituted with 2 mL saline if lyophilized." 
        },
        "notes": [
            "Avoid alcohol near dosing to reduce nausea risk.",
            "Coordinate with partner to set expectations around onset window.",
            "Monitor blood pressure if history of hypertension." 
        ]
    },
    {
        "id": "stack-dermal-renewal",
        "name": "Dermal Renewal System",
        "goal": "Accelerate skin rejuvenation following microneedling or laser procedures",
        "overview": "Pairs injectable GHK-Cu for systemic repair with topical Matrixyl 3000 serum and copper peptide masks for hydration.",
        "peptides": [
            {"name": "GHK-Cu Injectable", "dose": "200 mcg daily", "timing": "Evening"},
            {"name": "Matrixyl 3000", "dose": "Topical twice daily", "timing": "Morning & night"},
            {"name": "Copper Tripeptide Mask", "dose": "Mask 2-3x weekly", "timing": "Evening post-procedure"}
        ],
        "schedule": [
            {"day": "Daily", "instructions": "Morning: cleanse, apply Matrixyl 3000, follow with SPF."},
            {"day": "Daily", "instructions": "Evening: inject GHK-Cu, apply Matrixyl 3000, seal with moisturizer."},
            {"day": "Mon/Wed/Fri", "instructions": "Apply copper peptide mask for 20 minutes after gentle exfoliation."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 5.0,
            "instructions": "Reconstitute GHK-Cu injectable with 2 mL bacteriostatic water. Store topicals per manufacturer; no reconstitution required." 
        },
        "notes": [
            "Pause retinoids 48 hours before and after procedures.",
            "Maintain protein intake and vitamin C to support collagen.",
            "Use new needles for each injection to prevent irritation." 
        ]
    },
    {
        "id": "stack-cardio-balance",
        "name": "Cardiometabolic Balance",
        "goal": "Enhance vascular health while supporting lipid and glucose markers",
        "overview": "Angiotensin (1-7) keeps blood pressure in range, Adiponectin Modulator optimizes lipids, and MOTS-c improves mitochondrial glucose handling.",
        "peptides": [
            {"name": "Angiotensin (1-7)", "dose": "400 mcg daily", "timing": "Morning"},
            {"name": "Adiponectin Modulator", "dose": "5 mg oral daily", "timing": "With breakfast"},
            {"name": "MOTS-c", "dose": "10 mg weekly", "timing": "Monday 07:00"}
        ],
        "schedule": [
            {"day": "Daily", "instructions": "Take Angiotensin (1-7) upon waking and Adiponectin Modulator with breakfast."},
            {"day": "Monday", "instructions": "Inject MOTS-c before cardio session."},
            {"day": "Weekly", "instructions": "Track blood pressure and fasting glucose each Sunday morning."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 2.5,
            "instructions": "Reconstitute Angiotensin (1-7) and MOTS-c with 2 mL bacteriostatic water. Oral Adiponectin Modulator comes ready to use." 
        },
        "notes": [
            "Maintain moderate sodium intake (2-2.5 g/day).",
            "Include 3 cardio sessions weekly emphasizing zone 2 heart rate.",
            "Repeat labs at week 12 to measure lipid and glucose shifts." 
        ]
    },
    {
        "id": "stack-gut-rebuild",
        "name": "Gut Rebuild Intensive",
        "goal": "Repair intestinal barrier and normalize motility",
        "overview": "Combines oral BPC-157 and KPV with Gut Motility Peptide to heal mucosa while restoring migrating motor complex activity.",
        "peptides": [
            {"name": "BPC-157 Oral", "dose": "500 mcg daily", "timing": "Morning fasted"},
            {"name": "KPV Oral", "dose": "500 mcg daily", "timing": "Evening"},
            {"name": "Gut Motility Peptide", "dose": "100 mcg nightly", "timing": "30 minutes before bed"}
        ],
        "schedule": [
            {"day": "Morning", "instructions": "Take BPC-157 with a glass of water before breakfast."},
            {"day": "Evening", "instructions": "Dose KPV with last meal to calm inflammation."},
            {"day": "Night", "instructions": "Administer Gut Motility Peptide before bed followed by 12-hour fasting window."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 2.0,
            "instructions": "Gut Motility Peptide requires 1 mL bacteriostatic water; oral capsules are ready to use." 
        },
        "notes": [
            "Eliminate trigger foods (gluten, dairy) during the 8-week rebuild.",
            "Add probiotics on alternate days to recolonize beneficial flora.",
            "Track symptom scores weekly to gauge improvements." 
        ]
    },
    {
        "id": "stack-longevity-core",
        "name": "Longevity Core Cycle",
        "goal": "Support cellular energy, circadian rhythm, and mitochondrial function",
        "overview": "Epitalon resets circadian rhythm, Humanin protects mitochondria, and NAD+ Peptide Catalyst boosts sirtuins for global cellular upkeep.",
        "peptides": [
            {"name": "Epitalon", "dose": "10 mg nightly", "timing": "Evening"},
            {"name": "Humanin", "dose": "12 mg weekly", "timing": "Monday 08:00"},
            {"name": "NAD+ Peptide Catalyst", "dose": "1 mL IM twice weekly", "timing": "Tuesday & Friday 07:30"}
        ],
        "schedule": [
            {"day": "Nightly", "instructions": "Administer Epitalon before bed for 20 days then pause 4 months."},
            {"day": "Monday", "instructions": "Inject Humanin prior to fasted cardio."},
            {"day": "Tue/Fri", "instructions": "Deliver NAD+ Peptide Catalyst intramuscularly; chase with 500 mL water."}
        ],
        "reconstitution": {
            "diluent": "Sterile saline",
            "volume_ml": 2.0,
            "instructions": "Reconstitute Epitalon and Humanin with 2 mL sterile saline each. NAD+ Catalyst arrives premixed; protect from light." 
        },
        "notes": [
            "Pair with quarterly lab panels (CBC, CMP, NAD metabolite testing).",
            "Aim for 7-8 hours of sleep nightly to potentiate Epitalon.",
            "Include resistance training 3x weekly to leverage mitochondrial signaling." 
        ]
    },
    {
        "id": "stack-athletic-recovery",
        "name": "Advanced Athletic Recovery",
        "goal": "Accelerate soft tissue repair and muscle growth between intense training blocks",
        "overview": "TB-500 and BPC-157 target connective tissue while IGF-1 LR3 drives nutrient partitioning for muscle repair.",
        "peptides": [
            {"name": "TB-500 (Thymosin Beta-4 Fragment)", "dose": "2 mg twice weekly", "timing": "Mon/Thu"},
            {"name": "BPC-157", "dose": "250 mcg twice daily", "timing": "Morning & evening"},
            {"name": "IGF-1 LR3", "dose": "40 mcg post-workout", "timing": "Training days"}
        ],
        "schedule": [
            {"day": "Mon/Thu", "instructions": "Administer TB-500 post-therapy or training."},
            {"day": "Daily", "instructions": "Use BPC-157 near injury sites morning and night."},
            {"day": "Training Days", "instructions": "Inject IGF-1 LR3 immediately post-workout with carb/protein meal."}
        ],
        "reconstitution": {
            "diluent": "Bacteriostatic water",
            "volume_ml": 3.0,
            "instructions": "Reconstitute each vial with 2 mL bacteriostatic water; calculate per-injection volume using calculator for precise dosing." 
        },
        "notes": [
            "Implement deload every 6 weeks to avoid overtraining.",
            "Track morning HRV to gauge recovery status.",
            "Consume 0.3 g/kg protein within 30 minutes post training." 
        ]
    }
]


def build_peptide(entry):
    defaults = category_defaults[entry["category"]]
    description = f"{entry['name']} is {defaults['base_overview']} It focuses on {entry['focus']}."
    tags = [entry["category"]]
    for fragment in entry["focus"].replace("/", ",").replace("&", " and ").split(","):
        token = fragment.strip()
        if token and token not in tags:
            tags.append(token)
    return {
        "id": entry["id"],
        "name": entry["name"],
        "category": entry["category"],
        "mechanism": entry["mechanism"],
        "focus": entry["focus"],
        "description": description,
        "keyBenefits": entry["benefits"],
        "dosing": {
            "loading": entry["loading"],
            "maintenance": entry["maintenance"],
            "timing": entry["timing"],
        },
        "reconstitution": {
            "diluent": defaults["diluent"],
            "recommendedVolumeMl": defaults["volume_ml"],
            "steps": defaults["base_steps"],
            "notes": "Use sterile technique and refrigerate reconstituted peptide unless otherwise specified."
        },
        "safetyNotes": entry["notes"],
        "tags": tags,
    }


peptides = [build_peptide(item) for item in peptide_definitions]
peptides.sort(key=lambda p: p["name"].lower())

payload = (
    "export const peptides = " + json.dumps(peptides, indent=2) + ";\n\n"
    "export const stackProtocols = " + json.dumps(stack_protocols, indent=2) + ";\n"
)

DATA_FILE.write_text(payload)

print(f"Wrote {len(peptides)} peptides and {len(stack_protocols)} stack protocols to {DATA_FILE}")
